on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter test
    - name: Repository Dispatch
      if: success()
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        token: ${{ secrets.TOKEN }}
        repository: ${{ github.repository }}
        event-type: cd
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'